### ISSUE TITLE
Error in csem with .id

### ISSUE THREAD

**Issue by Jant2024** [FloSchuberth/cSEM#545]
Hello,

I am trying to run multi-group analysis. The csem function works normally with my model, but returns an error when defining .id for a group analysis. I have tried simplifying the model, but the error comes and goes (with the same code sometimes the code runs, sometimes it doesn't) and produces this:

Error in W[block, indicators] <- solve(.S[indicators, indicators]) %*%  : 
  NAs are not allowed in subscripted assignments
In addition: Warning message:
In cor(.X_cleaned) : the standard deviation is zero

**I attach an anonymised sample of my data and the code below:**

[AnonymousAll_groups_cleaned.csv](https://github.com/user-attachments/files/16904765/AnonymousAll_groups_cleaned.csv)

anonydata<-read.csv("C:/Documents/Data/AnonymousAll_groups_cleaned.csv", header=TRUE, sep=",")
anonydata$Z <- as.ordered(anonydata$Z)

.model <-"
#measurement model
LVA <~ A
LVHI <~ H + I
LVJ <~ J
LVK <~ K
LVL <~ L
LVMN <~ M + N
LVO <~ O
LVPQR <~ P + Q + R
LVSTU <~ S + T + U
LVV <~ V
LVWX <~ W + X

#structural model
LVA ~ LVK + LVL + LVO + LVPQR + LVWX + LVV
LVK ~ LVHI + LVJ + LVMN
LVL ~ LVK + LVMN
LVSTU ~ LVMN
LVPQR ~ LVL + LVSTU + LVWX
"

PLS <- csem(.model = .model, .data = anonydata, .resample_method = "bootstrap", .id = "Z")

**Comment by FloSchuberth** [comment]
Dear @Jant2024 
Thanks for the data this is really helpful.

If you run an MGA in cSEM. The model is estimated several times, one time for each group. The problem is that the groups Z=1 and Z=6 only consists of two observations
> table(anonydata$Z)

 1  2  3  4  5  6 
 2 15 80 81 20  2 

Therefore, you encounter problems as the correlation matrix is no longer of full rank and therefore certain calculation cannot performed. So it is not a problem of cSEM, but of the dataset. 

Similarly can happen if you run bootstrap for a dataset with only a few observations relative to the number of variables in the model. For instance, even I can estimate the model for group 2
PLS <- csem(.model = .model, .data = anonydata[anonydata$Z==2,], .resample_method = "none")

If bootstrap is used, I encounter the same problem.  

I am sorry, but there I cannot really help you.

**Comment by Jant2024** [comment]
Hi Flo,

Many thanks for checking this out. The issue makes sense and the function runs fine when I remove the groups with low observation counts.
Thanks!
Josh
